Repository AI-Project-Planner/project-planner-ui, pull requests merged in 2023-09, with the labels that each got.

#23 Sc/feature/projects history
  src/Components/App/App.tsx
  src/Components/FormPage/FormPage.tsx
  src/Components/FormPage/Questions/Question2.tsx
  src/Components/HomePage/HomePage.css
  src/Components/Menu/Menu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/ProjectsAll/ProjectsAll.tsx
  src/Components/Results/Results.css
  src/Components/Results/Results.tsx
  src/Components/SavedPage/SavedPage.css
  src/Components/SavedPage/SavedProject/SavedProject.tsx
Labels: new feature, FE

#26 Sc/testing/projects history
  cypress/e2e/all-projects-history.cy.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/saved_spec.cy.ts
  src/Components/App/App.tsx
  src/Components/Menu/Menu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/ProjectsAll/ProjectsAll.tsx
  src/Components/Results/Results.tsx
  src/Components/Results/Timeline/Timeline.tsx
  src/Components/SavedPage/SavedPage.tsx
Labels: FE, testing

#29 Fr/feature/delete from history
  cypress/e2e/all-projects-history.cy.ts
  cypress/fixtures/unSavedProjects1.json
  src/Components/App/App.tsx
  src/Components/ProjectsAll/ProjectsAll.tsx
  src/Components/Results/Results.tsx
  src/Components/SingleProject/SingleProject.tsx
  src/Types/types.ts
  src/apiCalls.ts
Labels: new feature, FE

#38 Sc/refactor/first 9 components
  src/Components/App/App.tsx
  src/Components/FormPage/FormPage.tsx
  src/Components/FormPage/Questions/Question2.tsx
  src/Components/ProjectsAll/ProjectsAll.tsx
  src/Types/FormPageTypes.tsx
  src/apiCalls.ts
Labels: FE, refactoring
